# Position Controllers ---------------------------------------
robosense_controller:
  type: effort_controllers/JointPositionController
  joint: robosense_base_scan_joint
  pid: {p: 80.0, i: 100.0, d: 8.0, i_clamp_max: 100.0, i_clamp_min: -100.0}
